std::bad_exception *__fastcall sub_33D598(std::bad_exception *a1)
{
  std::bad_exception::~bad_exception(a1);
  sub_33AC2C(a1);
  return a1;
}
